version: '3.1'
services:
  postgres-jwt-auth:
    image: postgres:12.2-alpine
    ports:
      - "5435:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jwt-auth-server
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"